config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'places', to:'places#search'
  root 'breweries#index'

  resources :breweries do
	  post 'toggle_activity', on: :member
  end

  resources :users do
	  post 'toggle_account_suspended', on: :member
  end

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'ngbeerlist', to:'beers#nglist'

end

app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage

	has_many :memberships, dependent: :destroy
	has_many :ratings, dependent: :destroy   # käyttäjällä on monta ratingia
	has_secure_password

	validates :username, uniqueness: true,
		  length: { minimum: 3, maximum: 15 }
	validates :password, length: {minimum: 4},
			     format: { with: /(.*[A-Z].*[0-9]|.*[0-9].*[A-Z])/, message: "Must contain at least one number and capital letter"}

	def self.top(n)
		sorted = User.all.sort_by{ |b| -b.ratings.count }
		sorted[0, n]
	end

	def favorite_beer
		return nil if ratings.empty?   # palautetaan nil jos reittauksia ei ole
		ratings.order(score: :desc).limit(1).first.beer
	end

	def favorite_style
		return nil if ratings.empty?
		rated = ratings.map{ |r| r.beer.style }.uniq
		rated.sort_by { |style| -rating_of_style(style) }.first
	end

	def favorite_brewery
		return nil if ratings.empty?
		rated = ratings.map{ |r| r.beer.brewery }.uniq
		rated.sort_by { |brewery| -rating_of_brewery(brewery) }.first
	end

	private

	def rating_of_style(style)
		ratings_of = ratings.select{ |r| r.beer.style==style }
		ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
	end

	def rating_of_brewery(brewery)
		ratings_of = ratings.select{ |r| r.beer.brewery==brewery }
		ratings_of.map(&:score).inject(&:+) / ratings_of.count.to_f
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_is_admin , only: :toggle_account_suspended

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
	  
	  if current_user == @user
		  respond_to do |format|
			  if user_params[:username].nil? and @user == current_user and @user.update(user_params)
				  format.html { redirect_to @user, notice: 'User was successfully updated.' }
				  format.json { render :show, status: :ok, location: @user }
			  else
				  format.html { render :edit }
				  format.json { render json: @user.errors, status: :unprocessable_entity }
			  end
		  end
	  end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
	  if current_user == @user
		  session.destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
    end
  end

  # POST /users/:id/toggle_account_suspended
  def toggle_account_suspended
	  user = User.find(params[:id])
	  user.update_attribute :account_suspended, (not user.account_suspended)

	  new_status = user.account_suspended? ? "frozen" : "not frozen"

	  redirect_to :back, notice:"User is now #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
	    params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if @user.new_record? %>
	  <div class="field">
		  <%= f.label :username %><br />
		  <%= f.text_field :username %>
	  </div>

  <div class="field">
	  <%= f.label :password %><br />
	  <%= f.password_field :password %>

  <% else %>


  <div class="field">
	  <%= f.label 'New Password' %><br />
	  <%= f.password_field :password %>
  </div>
  <% end %>
  <div class="field">
	  <%= f.label :password_confirmation %><br />
	  <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
	  <%= f.submit class:"btn btn-primary" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class:"btn btn-primary" %>
<%= link_to 'Back', users_path, class:"btn btn-primary"  %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:'btn btn-primary' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:"btn btn-primary" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>
  <%= @user.username %>
  </h1>
</p>

<p>
has made <%= @user.ratings.count %> ratings, average <%= @user.average_rating %>
</p>

<p>
<% if @user.memberships.empty? %>
	not a member of any beer clubs
<% else %>
member of <% @user.memberships.each do |m| %>
		<%= link_to m.beer_club.name, beer_club_path(m.beer_club) %>
	  <% end %>
  <% end %>
</p>

<p>
<ul>
	<% @user.ratings.each do |rating| %>
		<li> <%= rating %> 
		<% if @user == current_user %>
		<%= link_to 'delete', rating, method: :delete, data: {confirm: 'Are you sure?' } %> 
		<% end %>
		</li>
	<% end %>
</ul>


</p>
<% if current_user.admin? %>
	<%= link_to "change freeze", toggle_account_suspended_user_path(@user.id), method: :post, class: "btn btn-danger" %>
<% end %>

<% if current_user == @user %>
<%= link_to 'Delete', user_path(current_user), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_user_path(@user), class:'btn btn-primary' %> 
<% end %>
<%= link_to 'Back', users_path, class:'btn btn-primary' %>